"""Learning roadmap content — ADF-first practical journey."""

ROADMAP = [
    {
        "id": "01",
        "icon": "🔄",
        "title": "ADF Basics",
        "desc": "ADF introduction, architecture, and core building blocks.",
        "syllabus_key": "adf",
    },
    {
        "id": "02",
        "icon": "🏭",
        "title": "ADF Pipelines",
        "desc": "Pipelines, activities, IR, dynamic content, incremental load, and frameworks.",
        "syllabus_key": "adf",
    },
    {
        "id": "03",
        "icon": "📝",
        "title": "ADF Assignments",
        "desc": "Hands-on ADF assignments to reinforce pipeline design skills.",
        "syllabus_key": "assignments_mod",
        "coming_soon": True,
    },
    {
        "id": "04",
        "icon": "🔥",
        "title": "Azure Databricks",
        "desc": "Workspace, clusters, notebooks, jobs, Unity Catalog, and workflows.",
        "syllabus_key": "databricks",
    },
    {
        "id": "05",
        "icon": "📝",
        "title": "Databricks Assignments",
        "desc": "Practical Databricks assignments for notebook and job workflows.",
        "syllabus_key": "assignments_mod",
        "coming_soon": True,
    },
    {
        "id": "06",
        "icon": "🗄️",
        "title": "SQL",
        "desc": "SQL fundamentals through window functions, optimization, and interview focus.",
        "syllabus_key": "sql",
    },
    {
        "id": "07",
        "icon": "📝",
        "title": "SQL Assignments",
        "desc": "Practical SQL assignment sets for data engineering scenarios.",
        "syllabus_key": "assignments_mod",
        "coming_soon": True,
    },
    {
        "id": "08",
        "icon": "📐",
        "title": "Data Modeling",
        "desc": "Facts, dimensions, star/snowflake schemas, and SCD patterns.",
        "syllabus_key": "data_modeling",
    },
    {
        "id": "09",
        "icon": "🐍",
        "title": "Python for Data Engineering",
        "desc": "Python essentials applied to scripting, JSON, APIs, and data workflows.",
        "syllabus_key": "python",
    },
    {
        "id": "10",
        "icon": "🔀",
        "title": "Git & GitHub",
        "desc": "Version control, branching, pull requests, and collaboration basics.",
        "syllabus_key": "devops",
    },
    {
        "id": "11",
        "icon": "📋",
        "title": "Scrum Fundamentals",
        "desc": "Agile delivery basics for data engineering project execution.",
        "syllabus_key": "devops",
    },
    {
        "id": "12",
        "icon": "⚡",
        "title": "Advanced Databricks",
        "desc": "Deeper Databricks, PySpark performance, and production patterns.",
        "syllabus_key": "databricks",
    },
    {
        "id": "13",
        "icon": "🧠",
        "title": "Advanced SQL",
        "desc": "Advanced querying, tuning, plans, and interview-grade SQL depth.",
        "syllabus_key": "sql",
    },
    {
        "id": "14",
        "icon": "🟢",
        "title": "Delta Lake",
        "desc": "ACID tables, MERGE, time travel, OPTIMIZE, Z-ORDER, and VACUUM.",
        "syllabus_key": "delta_lake",
    },
    {
        "id": "15",
        "icon": "🏗️",
        "title": "Medallion Architecture",
        "desc": "Bronze, Silver, and Gold layers for lakehouse delivery.",
        "syllabus_key": "medallion",
    },
    {
        "id": "16",
        "icon": "🔐",
        "title": "Security & Governance",
        "desc": "IAM, RBAC, ACL, Key Vault, managed identity, and Unity Catalog security.",
        "syllabus_key": "security",
    },
    {
        "id": "17",
        "icon": "🚀",
        "title": "CI/CD",
        "desc": "Git integration, environments, deployment, and CI/CD for data platforms.",
        "syllabus_key": "devops",
    },
    {
        "id": "18",
        "icon": "🎯",
        "title": "End-to-End Project",
        "desc": "Full project from business requirement to monitored production-style delivery.",
        "syllabus_key": "e2e_project",
        "coming_soon": True,
    },
    {
        "id": "19",
        "icon": "🎤",
        "title": "Interview Preparation",
        "desc": "Module-wise, scenario, architecture, troubleshooting, and mock interviews.",
        "syllabus_key": "interview_mod",
    },
]
