"""Complete syllabus — Modules 01–16 with nested topics."""

SYLLABUS = [
    {
        "key": "azure_fundamentals",
        "number": "01",
        "icon": "☁️",
        "title": "Azure Fundamentals",
        "description": "Build a solid Azure cloud foundation for data engineering work.",
        "topics": [
            "What is Cloud Computing?",
            "On-Premise vs Cloud",
            "IaaS vs PaaS vs SaaS",
            "Azure Global Infrastructure",
            "Regions",
            "Availability Zones",
            "Azure Tenant",
            "Subscription",
            "Resource Group",
            "Azure Resources",
            "Azure Portal",
            "Hands-on Lab",
        ],
    },
    {
        "key": "azure_storage",
        "number": "02",
        "icon": "💾",
        "title": "Azure Storage",
        "description": "Master Storage Accounts, Blob Storage, ADLS Gen2, access, and security.",
        "topics": [
            "Storage Overview",
            {
                "title": "Storage Account",
                "children": [
                    "What is Storage Account?",
                    "Storage Account Types",
                    "Performance",
                    "Replication",
                    "LRS",
                    "ZRS",
                    "GRS",
                    "RA-GRS",
                ],
            },
            {
                "title": "Azure Blob Storage",
                "children": [
                    "What is Blob?",
                    "Block Blob",
                    "Append Blob",
                    "Page Blob",
                    "Blob Lifecycle",
                ],
            },
            {
                "title": "Containers",
                "children": [
                    "What is Container?",
                    "Container vs Folder",
                    "Naming Conventions",
                ],
            },
            {
                "title": "ADLS Gen2",
                "children": [
                    "What is ADLS?",
                    "Hierarchical Namespace",
                    "Folder Structure",
                    "ADLS Architecture",
                    "ADLS Use Cases",
                ],
            },
            {"title": "Blob vs ADLS Gen2", "star": True},
            "Access Tiers",
            "RBAC",
            "ACL",
            "Authentication",
            "Storage Security",
        ],
    },
    {
        "key": "adf",
        "number": "03",
        "icon": "🔄",
        "title": "Azure Data Factory",
        "description": "Design, orchestrate, monitor, and optimize enterprise ADF pipelines.",
        "topics": [
            "ADF Introduction",
            "Why ADF?",
            "ADF Architecture",
            {
                "title": "ADF Core Components",
                "star": True,
                "children": [
                    "Pipeline",
                    "Activity",
                    "Dataset",
                    "Linked Service",
                    "Integration Runtime",
                    "Trigger",
                ],
            },
            {
                "title": "Linked Services",
                "children": [
                    "Azure Blob",
                    "ADLS Gen2",
                    "Azure SQL",
                    "SQL Server",
                    "Databricks",
                    "REST API",
                ],
            },
            {
                "title": "Datasets",
                "children": [
                    "Dataset Concept",
                    "Dataset Parameters",
                    "File Dataset",
                    "Table Dataset",
                    "Parameterized Dataset",
                ],
            },
            {
                "title": "Integration Runtime",
                "star": True,
                "children": [
                    "Azure IR",
                    "Self-Hosted IR",
                    "Azure-SSIS IR",
                    "IR Networking",
                    "IR Troubleshooting",
                ],
            },
            {
                "title": "Pipelines",
                "children": [
                    "Pipeline Basics",
                    "Pipeline Parameters",
                    "Pipeline Variables",
                    "Pipeline JSON",
                ],
            },
            {
                "title": "Copy Activity",
                "star": True,
                "children": [
                    "Source",
                    "Sink",
                    "Mapping",
                    "Schema Mapping",
                    "Auto Mapping",
                    "Fault Tolerance",
                    "Parallel Copy",
                    "DIU",
                    "Performance Tuning",
                ],
            },
            {
                "title": "Control Flow Activities",
                "children": [
                    "Lookup",
                    "Get Metadata",
                    "ForEach",
                    "If Condition",
                    "Switch",
                    "Until",
                    "Filter",
                    "Execute Pipeline",
                    "Wait",
                    "Set Variable",
                    "Fail",
                ],
            },
            {
                "title": "Dynamic Content",
                "star": True,
                "children": [
                    "Expressions",
                    "String Functions",
                    "Date Functions",
                    "Array Functions",
                    "Logical Functions",
                    "Conversion Functions",
                    "System Variables",
                    "Practical Expressions",
                ],
            },
            {
                "title": "Triggers",
                "children": [
                    "Manual Trigger",
                    "Schedule Trigger",
                    "Tumbling Window",
                    "Event Trigger",
                    "Trigger Parameters",
                ],
            },
            {
                "title": "ADF Transformations",
                "children": [
                    "Mapping Data Flow",
                    "Source",
                    "Select",
                    "Filter",
                    "Derived Column",
                    "Join",
                    "Aggregate",
                    "Lookup",
                    "Conditional Split",
                    "Sink",
                ],
            },
            {
                "title": "Incremental Loading",
                "star": True,
                "children": [
                    "Full Load",
                    "Incremental Load",
                    "Watermark",
                    "Last Modified Date",
                    "SQL Watermark",
                    "Metadata Table",
                ],
            },
            {
                "title": "CDC",
                "children": [
                    "What is CDC?",
                    "CDC vs Incremental Load",
                    "SQL CDC",
                    "ADF CDC Patterns",
                ],
            },
            {
                "title": "REST API Integration",
                "children": [
                    "API Basics",
                    "Authentication",
                    "Web Activity",
                    "REST Connector",
                    "Pagination",
                    "Token Handling",
                ],
            },
            {
                "title": "Metadata Driven Framework",
                "star": True,
                "stars": 3,
                "children": [
                    "Architecture",
                    "Configuration Table",
                    "Generic Pipeline",
                    "Dynamic Source",
                    "Dynamic Sink",
                    "End-to-End Framework",
                ],
            },
            "Error Handling",
            "Retry Mechanism",
            "Logging",
            "Monitoring",
            "Alerts",
            "Performance Optimization",
            "Security",
            "Managed Identity",
            "Key Vault",
            "Git Integration",
            "CI/CD",
            "ADF Enterprise Project",
        ],
    },
    {
        "key": "sql",
        "number": "04",
        "icon": "🗄️",
        "title": "SQL",
        "description": "SQL for analytics, transformations, and data engineering interviews.",
        "topics": [
            "SQL Fundamentals",
            "SELECT",
            "WHERE",
            "GROUP BY",
            "HAVING",
            "ORDER BY",
            "Joins",
            "Subqueries",
            "CTE",
            "Temporary Tables",
            "Views",
            "Stored Procedures",
            "Functions",
            {"title": "Window Functions", "star": True},
            "Query Optimization",
            "Indexing",
            "Execution Plans",
            "SQL Interview Questions",
        ],
    },
    {
        "key": "data_modeling",
        "number": "05",
        "icon": "📐",
        "title": "Data Modeling",
        "description": "Design warehouse and lakehouse models used in real analytics platforms.",
        "topics": [
            "OLTP vs OLAP",
            "Data Warehouse",
            "Data Lake",
            "Lakehouse",
            "Fact Tables",
            "Dimension Tables",
            "Measures",
            "Grain",
            "Natural Key",
            "Surrogate Key",
            "Star Schema",
            "Snowflake Schema",
            "SCD Type 0",
            "SCD Type 1",
            {"title": "SCD Type 2", "star": True},
            "SCD Type 3",
            "Real-World Data Model",
        ],
    },
    {
        "key": "python",
        "number": "06",
        "icon": "🐍",
        "title": "Python",
        "description": "Python fundamentals applied to modern data engineering workflows.",
        "topics": [
            "Python Fundamentals",
            "Variables",
            "Data Types",
            "Lists",
            "Tuples",
            "Sets",
            "Dictionaries",
            "Conditions",
            "Loops",
            "Functions",
            "Lambda",
            "Exception Handling",
            "File Handling",
            "JSON",
            "APIs",
            "Modules",
            "OOP Basics",
            "Python for Data Engineering",
        ],
    },
    {
        "key": "pyspark",
        "number": "07",
        "icon": "⚡",
        "title": "PySpark",
        "description": "Process large datasets with Spark architecture, DataFrames, and optimization.",
        "topics": [
            "Why Spark?",
            "Spark Architecture",
            "Driver",
            "Executor",
            "Worker",
            "Cluster",
            "DAG",
            "Lazy Evaluation",
            "DataFrames",
            "Reading Data",
            "Writing Data",
            "select()",
            "filter()",
            "withColumn()",
            "groupBy()",
            "agg()",
            "Joins",
            "Window Functions",
            "UDF",
            "Array",
            "Struct",
            "Map",
            "Explode",
            "Repartition",
            "Coalesce",
            "Broadcast Join",
            "Cache",
            "Persist",
            "Shuffle",
            "Performance Optimization",
        ],
    },
    {
        "key": "databricks",
        "number": "08",
        "icon": "🔥",
        "title": "Azure Databricks",
        "description": "Workspaces, compute, jobs, Unity Catalog, SQL, and ADF integration.",
        "topics": [
            "Databricks Introduction",
            "Workspace",
            "Workspace Objects",
            "Notebooks",
            "Compute",
            "Clusters",
            "Cluster Types",
            "Cluster Configuration",
            "Jobs",
            "Workflows",
            "Libraries",
            "Secrets",
            {
                "title": "Unity Catalog",
                "star": True,
                "children": [
                    "Metastore",
                    "Catalog",
                    "Schema",
                    "Tables",
                    "Views",
                    "Permissions",
                ],
            },
            "External Locations",
            "Managed vs External Tables",
            "Databricks SQL",
            "Databricks Workflows",
            "ADF + Databricks Integration",
            "Databricks Project",
        ],
    },
    {
        "key": "delta_lake",
        "number": "09",
        "icon": "🟢",
        "title": "Delta Lake",
        "description": "Reliable lakehouse tables with ACID transactions and performance features.",
        "topics": [
            "What is Delta Lake?",
            "Parquet vs Delta",
            "ACID Transactions",
            "Delta Transaction Log",
            "Create Delta Table",
            "Read Delta",
            "Write Delta",
            "MERGE",
            "UPSERT",
            "DELETE",
            "UPDATE",
            "Time Travel",
            "OPTIMIZE",
            "Z-ORDER",
            "VACUUM",
            "Delta Lake Performance",
        ],
    },
    {
        "key": "medallion",
        "number": "10",
        "icon": "🏗️",
        "title": "Medallion Architecture",
        "description": "Design Bronze, Silver, and Gold layers for trustworthy analytics delivery.",
        "topics": [
            "Lakehouse Architecture",
            "Bronze Layer",
            "Silver Layer",
            "Gold Layer",
            "Raw Data",
            "Cleansed Data",
            "Business Data",
            "Data Quality",
            "End-to-End Medallion Project",
        ],
    },
    {
        "key": "security",
        "number": "11",
        "icon": "🔐",
        "title": "Security & Governance",
        "description": "Secure Azure data platforms with identity, secrets, encryption, and governance.",
        "topics": [
            "Azure IAM",
            "RBAC",
            "ACL",
            "Managed Identity",
            "Service Principal",
            "Azure Key Vault",
            "Secrets",
            "Encryption",
            "Unity Catalog Security",
            "Data Governance",
        ],
    },
    {
        "key": "devops",
        "number": "12",
        "icon": "🚀",
        "title": "DevOps & CI/CD",
        "description": "Git, GitHub, ADF Git integration, environments, and CI/CD concepts.",
        "topics": [
            "Git Fundamentals",
            "GitHub",
            "Branching",
            "Pull Requests",
            "ADF Git Integration",
            "Deployment",
            "Environment Management",
            "DEV / TEST / PROD",
            "CI/CD Pipeline",
            "Infrastructure Concepts",
            "Scrum Fundamentals",
            "Agile Delivery Basics",
        ],
    },
    {
        "key": "e2e_project",
        "number": "13",
        "icon": "🎯",
        "title": "End-to-End Project",
        "description": "Implement a full Azure data engineering project from requirement to architecture.",
        "topics": [
            "Project Introduction",
            "Business Requirement",
            "Source Systems",
            "Architecture",
            "Data Sources",
            "ADLS Setup",
            "ADF Ingestion",
            "Bronze Layer",
            "Silver Layer",
            "Gold Layer",
            "Data Modeling",
            "Incremental Load",
            "Data Quality",
            "Error Handling",
            "Monitoring",
            "CI/CD",
            "Final Architecture",
        ],
    },
    {
        "key": "labs",
        "number": "14",
        "icon": "🧪",
        "title": "Hands-on Labs",
        "description": "Guided labs across Azure, ADF, SQL, Python, PySpark, Databricks, and E2E flows.",
        "topics": [
            "Azure Labs",
            "ADLS Labs",
            "ADF Labs",
            "SQL Labs",
            "Python Labs",
            "PySpark Labs",
            "Databricks Labs",
            "End-to-End Labs",
        ],
    },
    {
        "key": "assignments_mod",
        "number": "15",
        "icon": "📝",
        "title": "Assignments",
        "description": "Assignment tracks across Azure, ADF, SQL, Python, PySpark, Databricks, and project.",
        "topics": [
            "Azure Assignments",
            "ADF Assignments",
            "SQL Assignments",
            "Python Assignments",
            "PySpark Assignments",
            "Databricks Assignments",
            "Project Assignments",
        ],
    },
    {
        "key": "interview_mod",
        "number": "16",
        "icon": "🎤",
        "title": "Interview Preparation",
        "description": "Technical, scenario, architecture, troubleshooting, and mock interview readiness.",
        "topics": [
            "Azure Questions",
            "ADLS Questions",
            "ADF Questions",
            "SQL Questions",
            "Python Questions",
            "PySpark Questions",
            "Databricks Questions",
            "Data Modeling Questions",
            "Scenario-Based Questions",
            "Architecture Questions",
            "Troubleshooting Questions",
            "Mock Interviews",
        ],
    },
]


def get_module_by_key(key: str) -> dict | None:
    for module in SYLLABUS:
        if module["key"] == key:
            return module
    return None


def count_topics(topics: list) -> int:
    total = 0
    for topic in topics:
        if isinstance(topic, str):
            total += 1
        elif isinstance(topic, dict):
            total += 1
            total += count_topics(topic.get("children", []))
    return total
